services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: minhhn
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: oncogenomics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oncogenomics_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U minhhn" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  oncogenomics_net:
    driver: bridge